### ISSUE TITLE
Analysis modularization distribution

### ISSUE THREAD

**Issue by AReyH** [UBC-MDS/GoT-fatality-prediction#13]
Hi, team!

I wanted to see what could be a good way to distribute the code modularization, in a way everyone feels comfortable, and has a similar workload.

Our analysis is divided into several blocks:

* Data ingestion
* Data preprocessing
* EDA
* Modelling
* Results interpreting

I would feel the most comfortable modularizing the data preprocessing part, but I am open to suggestions!

**Comment by 786213750** [comment]
Did tiff post a example of this?

**Comment by AReyH** [comment]
> Did tiff post a example of this?

What do you mean? We just have to modularize our existing code from last week.

**Comment by 786213750** [comment]
> > Did tiff post a example of this?
> 
> What do you mean? We just have to modularize our existing code from last week.

Yes, but did she provide any code sample so we can follow her style.

**Comment by AReyH** [comment]
> > > Did tiff post a example of this?
> > 
> > 
> > What do you mean? We just have to modularize our existing code from last week.
> 
> Yes, but did she provide any code sample so we can follow her style.

She has her cancer prediction repo available so we can follow that style.

**Comment by 786213750** [comment]
can you pin the link here?

**Comment by 786213750** [comment]
> can you pin the link here?

https://github.com/ttimbers/breast_cancer_predictor/tree/master/src

**Comment by sifanzzz** [comment]
My thought here is that we can create a container together(as was planned yesterday) and maybe also abstract some code from code document together as well.
After that, we can split the code file and write tests on the parts (as recommended in Milestone2 requirement file):

- Saving and loading data
- Data validation
- Cleaning and transforming data
- Models

I remember yesterday at lab she said we only need to take 4 pieces of the work and develop 4 functions.
What do you think?

**Comment by ianm99** [comment]
Hey everyone! I'm going to modularize the code that summarizes the output of random_search.cv_results_
![image](https://github.com/UBC-MDS/GoT-fatality-prediction/assets/143557285/4559e8a7-8646-48a0-af34-abcde9e703c9)
lemme know if this conflicts with anyone else's work
