### ISSUE TITLE
test-short_results

### ISSUE THREAD

**Issue by ianm99** [UBC-MDS/GoT-fatality-prediction#15]
![image](https://github.com/UBC-MDS/GoT-fatality-prediction/assets/143557285/a357a545-7c72-488a-bb18-233309aa3665)
So I perhaps foolishly created a function which takes as input the output of a call to RandomizedSearchCV. Coming up with some test data for this function is a bit onerous since I have to create fake training data, build a fake pipeline, come up with a fake parameter distribution dictionary, and finally call RAndomizedSearchCV on all that. I wondered if anyone sees an easier way around this problem? Is it reasonable to take the output of thomas' model test as the input here?

**Comment by 786213750** [comment]
I think the structure for getting result is a function with input of a trained model(I will provide u) and test data(u can create fake) and output is a dataframe with all the score and/or a plot for showing result.

**Comment by 786213750** [comment]
@ianm99 you can mark this a closed
