### ISSUE TITLE
EDA code is not at src

### ISSUE THREAD

**Issue by 786213750** [UBC-MDS/GoT-fatality-prediction#43]
![image](https://github.com/UBC-MDS/GoT-fatality-prediction/assets/31583827/2cba62b7-7530-45d1-9686-615ff297176d)
@sifanzzz Where is the EDA src code?

**Comment by sifanzzz** [comment]
the one named visualize_correlation.py

**Comment by 786213750** [comment]
oh, I see. Can you delete the test_for_eda from the src?

**Comment by sifanzzz** [comment]
sure
